networks:
  mon-reseau:
    driver: bridge

services:
  conteneur1:
    image: ubuntu
    command: tail -f /dev/null
    networks:
      - mon-reseau
  
  conteneur2:
    image: ubuntu
    command: tail -f /dev/null
    networks:
      - mon-reseau